Adding boxplot microservice
uber-workflow/report-benchmarks pull request #1
Opened 2019-06-28 17:44 UTC by LambStack

Microservice to generate boxplots based on json data, see it in action at here's an example boxplot
![Boxplot](https://scheming.scheming.workers.dev/?json=%7B%22chartType%22%3A%22boxplot%22%2C%22title%22%3A%22incremental%22%2C%22labels%22%3A%5B%22head%22%2C%22base%22%5D%2C%22data%22%3A%5B%5B3367%2C3655%2C3420%2C3450%2C3440%5D%2C%5B3367%2C3655%2C3430%2C3451%2C3420%5D%5D%7D)

2019-06-28 17:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber-workflow/report-benchmarks?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber-workflow/report-benchmarks?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber-workflow/report-benchmarks?pullRequest=1) it.</sub>

2019-06-29 00:10 UTC, rtsao requested changes
This is really cool!

A few things:

- I think the size calculation might be a bit off, for example: https://scheming.scheming.workers.dev/?json={%22chartType%22:%22boxplot%22,%22title%22:%22incremental%22,%22labels%22:[%22head%22,%22base%22],%22data%22:[[3367,3655,3420,3450,3440],[2127,2655,2430,2451,2420]]}

- I suspect that making time the horizontal axis (or making this configurable) might be preferable because:
   - Most comparison will probably be between just two data sets. By stacking the box plots on top of each other, the chart will be wider than tall, which should fit better into a GitHub comment (and allow for room for the time axis).

- If it looks good with our small sample sizes, I think a https://en.wikipedia.org/wiki/Violin_plot (as seen on https://vx-demo.now.sh/boxplot) might be strictly better than a box plot since it conveys more information about the distribution of values. More info: https://blog.bioturing.com/2018/05/16/5-reasons-you-should-use-a-violin-graph/

- I'm a bit skeptical of the utility of the default `±1.5 * IQR` whiskers as calculated by [the `computeStats` function from `vx`](https://github.com/hshoff/vx/blob/master/packages/vx-boxplot/src/util/computeStats.js#L8-L9). I think this is atypical (and not very sensible). Instead, I think we should consider using the whiskers for a different value. My understanding is for conventional "Tukey boxplot", the whiskers are for the lowest and highest values *within* `±1.5*IQR`, not `±1.5*IQR` itself. Also, I wonder if `MEAN±STDEV` or just straight up min/max values might be more appropriate with a smaller data set. More info here: https://www.graphpad.com/support/faq/five-ways-to-plot-whiskers-in-box-and-whisker-plots/ and https://en.wikipedia.org/wiki/Box_plot#Types

- It would be really nice if labels weren't overlapping. Perhaps something like this: https://bl.ocks.org/martinjc/980a2fcdbf0653c301dc2fb52750b0d9/https://gist.github.com/martinjc/980a2fcdbf0653c301dc2fb52750b0d9 where if labels overlap, they are spaced out.

- A minor thing, but having the two data sets be different colors might be useful, keeping in mind [accessible color choices for color blindness](https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0000HT#bboard_content), etc.

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "babel-preset-react": "^6.24.1",
I think this is unused (and even if was used, for Babel v7, the `@babel/preset-react` should be used instead).

```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "dom-to-image": "^2.6.0",
```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/index.js
> +const parseUrl = require("parse-url");
Unless there's a specific reason to use this package, it's probably preferable to use the standard, built-in URL parser: https://nodejs.org/api/url.html

2019-06-29 00:10 UTC, rtsao commented on scheming/index.js
> +function boxPlot(data, labels, title) {
It's uncommon for "regular" functions to return React elements (e.g. JSX/`React.createElement` call expressions).

For better composability within *other* components, it is more common to conform to the component function signature (taking in a `props` object).

So this would look like:

```js
function BoxPlot(props) {
  const {data, labels, title} = props;
  /* ... */
}

// And later:
ReactDOMServer.renderToStaticMarkup(
  <BoxPlot title="title" data={/* .. */} labels={/* ... */} />
);

// or in some other component:
function SomeOtherComponent(props) {
   return (
     <div>
       <BoxPlot title="title" data={/* .. */} labels={/* ... */} />
     </div>
}
```

2019-06-29 00:10 UTC, rtsao commented on scheming/index.js
> +    const output = ReactDOMServer.renderToString(
Two things:

1. `renderToString` is intended for producing markup that will eventually be hydrated via a client-side React. Instead, `renderToStaticMarkup` is for producing plain HTML/SVG that will be used completely outside of React.

```suggestion
    const output = ReactDOMServer.renderToStaticMarkup(
```

2. React also supports streaming server-side rendering, which you can pipe to the response. This way, the server can begin sending the response incrementally during render, without first having to wait for the entire render to complete.

I think Cloudflare Workers supports streaming responses: https://workers.cloudflare.com/docs/reference/runtime/apis/streams/

In this case you would use `React.renderToStaticNodeStream`: https://reactjs.org/docs/react-dom-server.html#rendertostaticnodestream

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "babel-core": "^6.26.3",
I think this is unused (and even if was used, for Babel v7, the `@babel/core` should be used instead).

```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "babel-preset-es2015": "^6.24.1",
I think this is unused (and even if it was used, for Babel v7, the `@babel/preset-es2015` should be used instead).

```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "@babel/preset-react": "^7.0.0",
Conventionally, buildtime-only dependencies are specified in `devDependencies`, as opposed to runtime dependencies (e.g. used in `require`) which are specified in `dependencies`.

So I think `@babel/preset-react` should be moved to `dependencies`.

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "@babel/preset-env": "^7.4.5",
I think this is unused

```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +    "parse-url": "^5.0.1",
As mentioned in an another comment, it's probably better to use the built-in standard URL object/parser.

```suggestion
```

2019-06-29 00:10 UTC, rtsao commented on scheming/index.js
> +    PADDING = 70;
Might be worth making these component props rather than hardcoded constants.

2019-06-29 00:10 UTC, rtsao commented on scheming/webpack.config.js
> +    // We no not want to minimize our code.
Why not? In production builds, I think minification would yield faster startup.

2019-06-29 00:10 UTC, rtsao commented on scheming/webpack.config.js
> +  stats: {
Is this the default? Perhaps this field could be omitted.

2019-06-29 00:10 UTC, rtsao commented on scheming/package.json
> +  "husky": {
(I know this was just in the default `wrangler` scaffold)

One concern I have with commit hooks is they can add friction to certain git operations (interactive rebase, bisect, etc.) This is especially problematic if what is enforced changes over time or is dependent on `node_modules` (which typically aren't checked into `git`).

It also probably makes more sense to configure these sort of things on a repo-wide basis. For now I'd recommend to just removing husky entirely.

2019-06-29 00:58 UTC, rtsao commented
Actually what might be optimal would be something like:

![violin plot](https://modeanalytics.com/api/modeanalytics/reports/f2a442bd3b9a/notebooks/164d001a768e/cells/504f2c540392/runs/56527c31f2d5/results/42166c8d4d37/result)

![violin plot](https://datavizproject.com/wp-content/uploads/2015/11/bean_plots4.png)

So the before/after are next to each other, with different series being different benchmarks (dev/dev-incremental/prod for various fixtures)

2019-07-01 17:12 UTC, LambStack commented
> Actually what might be optimal would be something like:
> ...
> So the before/after are next to each other, with different series being different benchmarks (dev/dev-incremental/prod for various fixtures)

I think it may be impractical to have all of the charts appear in the same svg. The smallest one ranges from about 500 to 800, while the largest frequently goes over 100,000. Instead, I think it'd be good to just make 4 images, one for each type of build.

[//]: # (BOXPLOT)
 ![Boxplot](https://scheming.scheming.workers.dev/?json=%7B%22chartType%22%3A%22boxplot%22%2C%22title%22%3A%22cached%22%2C%22labels%22%3A%5B%22head%22%2C%22base%22%5D%2C%22data%22%3A%5B%5B5609%2C5594%2C5720%2C5685%2C5532%5D%2C%5B5709%2C5695%2C5751%2C5686%2C5632%5D%5D%7D)  ![Boxplot](https://scheming.scheming.workers.dev/?json=%7B%22chartType%22%3A%22boxplot%22%2C%22title%22%3A%22uncached%22%2C%22labels%22%3A%5B%22head%22%2C%22base%22%5D%2C%22data%22%3A%5B%5B83458%2C83101%2C82820%2C84248%2C85272%5D%2C%5B83488%2C83811%2C82891%2C84238%2C85472%5D%5D%7D)  ![Boxplot](https://scheming.scheming.workers.dev/?json=%7B%22chartType%22%3A%22boxplot%22%2C%22title%22%3A%22incremental%22%2C%22labels%22%3A%5B%22head%22%2C%22base%22%5D%2C%22data%22%3A%5B%5B3367%2C3655%2C3420%2C3450%2C3440%5D%2C%5B3367%2C3655%2C3430%2C3451%2C3420%5D%5D%7D)  ![Boxplot](https://scheming.scheming.workers.dev/?json=%7B%22chartType%22%3A%22boxplot%22%2C%22title%22%3A%22production%22%2C%22labels%22%3A%5B%22head%22%2C%22base%22%5D%2C%22data%22%3A%5B%5B135030%2C133188%2C133753%2C132276%2C141104%5D%2C%5B135039%2C133978%2C133954%2C132676%2C141004%5D%5D%7D)

Otherwise smaller values would get lost in between the margins of the larger ones.

2019-07-01 18:28 UTC, LambStack commented
> * If it looks good with our small sample sizes, I think a https://en.wikipedia.org/wiki/Violin_plot (as seen on https://vx-demo.now.sh/boxplot) might be strictly better than a box plot since it conveys more information about the distribution of values. More info: https://blog.bioturing.com/2018/05/16/5-reasons-you-should-use-a-violin-graph/

Since we are displaying all the data points, I don't think adding the violin plot adds any information. 
<img width="213" alt="Screen Shot 2019-07-01 at 11 25 46 AM" src="https://user-images.githubusercontent.com/24273374/60458260-fcf7cd00-9bf2-11e9-98c9-ce42d4a2d707.png">

<img width="189" alt="Screen Shot 2019-07-01 at 11 23 27 AM" src="https://user-images.githubusercontent.com/24273374/60458202-d2a60f80-9bf2-11e9-9d40-70d1a2a9d394.png">

Although, I think it does look better, and it would help in case we ever want to use this to display more data.

2019-07-01 23:33 UTC, LambStack commented on scheming/webpack.config.js
> +    // We no not want to minimize our code.
This was for development, so I could see more helpful bugs. I forgot to remove it.

2019-07-02 00:09 UTC, rtsao commented
> Since we are displaying all the data points, I don't think adding the violin plot adds any information.

IMO the violin plot still helps in the case of having overlapping points (e.g. `[3,5,7,7,7]` would only really show 3 points but the distribution skews towards 7)

2019-07-02 17:46 UTC, rtsao approved these changes

2019-07-02 17:51 UTC, merged